Update RAX3000M-eMMC_XR30-eMMC-hanwckf.yml

diff --git a/.github/workflows/RAX3000M-eMMC_XR30-eMMC-hanwckf.yml b/.github/workflows/RAX3000M-eMMC_XR30-eMMC-hanwckf.yml
--- a/.github/workflows/RAX3000M-eMMC_XR30-eMMC-hanwckf.yml
+++ b/.github/workflows/RAX3000M-eMMC_XR30-eMMC-hanwckf.yml
@@ -267,29 +267,29 @@ jobs:
       
       
     - name: 整理文件并重命名
-  id: organize
-  if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
-  run: | 
-    mapfile -t devices < <(grep '^CONFIG_TARGET_DEVICE.*=y' openwrt/.config | sed -r 's/.*DEVICE_(.*)=y/\1/')
-    cd openwrt/bin/targets/*/*
-    rm -rf packages
-    error_occurred=false
-    for val in "${devices[@]}"; do
-      for file in *${val}*; do
-        new_name="${{ env.FILE_DATE }}-${{ env.OPENWRT_NAME }}-${val}${{ env.WIFI_VERSION }}${{ env.EEPROM }}${{ env.BUILD_DOCKERMAN }}${file#*$val}"
-        mv "$file" "$new_name" || {
-          echo "Error: Failed to rename file $file"
-          error_occurred=true
-        }
-      done
-      echo "$val"
-    done
-    if [ "$error_occurred" = true ]; then
-      echo "status=failure" >> $GITHUB_OUTPUT
-    else
-      echo "FIRMWARE=$PWD" >> $GITHUB_ENV
-      echo "status=success" >> $GITHUB_OUTPUT
-    fi
+      id: organize
+      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
+      run: | 
+        mapfile -t devices < <(grep '^CONFIG_TARGET_DEVICE.*=y' openwrt/.config | sed -r 's/.*DEVICE_(.*)=y/\1/')
+        cd openwrt/bin/targets/*/*
+        rm -rf packages
+        error_occurred=false
+        for val in "${devices[@]}"; do
+          for file in *${val}*; do
+            new_name="${{ env.FILE_DATE }}-${{ env.OPENWRT_NAME }}-${val}${{ env.WIFI_VERSION }}${{ env.EEPROM }}${{ env.BUILD_DOCKERMAN }}${file#*$val}"
+            mv "$file" "$new_name" || {
+              echo "Error: Failed to rename file $file"
+              error_occurred=true
+            }
+          done
+          echo "$val"
+        done
+        if [ "$error_occurred" = true ]; then
+          echo "status=failure" >> $GITHUB_OUTPUT
+        else
+          echo "FIRMWARE=$PWD" >> $GITHUB_ENV
+          echo "status=success" >> $GITHUB_OUTPUT
+        fi
 
     - name: 打包上传固件到Actions Artifacts
       uses: actions/upload-artifact@main
